In [1]:
import numpy as np
import pandas as pd

In [3]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}

df = pd.DataFrame(data)

In [5]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [7]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [8]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [11]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [9]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [12]:
df.dropna(thresh=3)                        #print row that have no. of non-null values

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [13]:
df.dropna(thresh=4)

     A  B    C    D
0  1.0  1  1.0  1.0

In [15]:
df.dropna(thresh=5)

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [17]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [18]:
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [20]:
df.fillna({'A':10,'B':20,'C':30,'D':40})

      A  B     C     D
0   1.0  1   1.0   1.0
1   2.0  2   2.0  40.0
2  10.0  3   3.0  40.0
3   4.0  4  30.0  40.0
4   5.0  5  30.0   5.0