In [36]:
import numpy as np
import pandas as pd

In [37]:
data = {
    'Name' : ['Piku','kungfu','kunu','lama'],
    'Age' : [23,25,31,33],
    'Country' : ['Turky','London','Dubai','Bali'],
    'salary': [65000,50000,45000,11110]
}

df = pd.DataFrame(data)
df

     Name  Age Country  salary
0    Piku   23   Turky   65000
1  kungfu   25  London   50000
2    kunu   31   Dubai   45000
3    lama   33    Bali   11110

In [38]:
data_list = [
    ['Piku', 23, 'Turky', 65000],
    ['kungfu', 25,'London',	50000],
    ['kunu', 31,'Dubai', 45000],
    ['lama', 33, 'Bali', 11110]
]
column = ['name','age','country','salary']
df2 = pd.DataFrame(data_list,columns=column)
df2

     name  age country  salary
0    Piku   23   Turky   65000
1  kungfu   25  London   50000
2    kunu   31   Dubai   45000
3    lama   33    Bali   11110

In [39]:
df

     Name  Age Country  salary
0    Piku   23   Turky   65000
1  kungfu   25  London   50000
2    kunu   31   Dubai   45000
3    lama   33    Bali   11110

In [40]:
df[['Name','Country']]                                     #selecting colomuns

     Name Country
0    Piku   Turky
1  kungfu  London
2    kunu   Dubai
3    lama    Bali

In [41]:
df["profession"] = ["Data Science","Web developer","UI/UX Designer","Game Developer"]
df                                       #creating columns

     Name  Age Country  salary      profession
0    Piku   23   Turky   65000    Data Science
1  kungfu   25  London   50000   Web developer
2    kunu   31   Dubai   45000  UI/UX Designer
3    lama   33    Bali   11110  Game Developer

In [42]:
df.drop(["profession"],axis=1,inplace=True)             #removing columns

In [43]:
df

     Name  Age Country  salary
0    Piku   23   Turky   65000
1  kungfu   25  London   50000
2    kunu   31   Dubai   45000
3    lama   33    Bali   11110

In [44]:
df.drop([1],axis=0)                                 #removing rows

   Name  Age Country  salary
0  Piku   23   Turky   65000
2  kunu   31   Dubai   45000
3  lama   33    Bali   11110

In [45]:
df

     Name  Age Country  salary
0    Piku   23   Turky   65000
1  kungfu   25  London   50000
2    kunu   31   Dubai   45000
3    lama   33    Bali   11110

In [46]:
df2

     name  age country  salary
0    Piku   23   Turky   65000
1  kungfu   25  London   50000
2    kunu   31   Dubai   45000
3    lama   33    Bali   11110

In [47]:
#selecting rows
df2.loc[[1]]

     name  age country  salary
1  kungfu   25  London   50000

In [48]:
df2.loc[[0,1]][["name","salary"]]

     name  salary
0    Piku   65000
1  kungfu   50000

In [49]:
df2.loc[[2,3]][["name","age"]]

   name  age
2  kunu   31
3  lama   33

In [50]:
df

     Name  Age Country  salary
0    Piku   23   Turky   65000
1  kungfu   25  London   50000
2    kunu   31   Dubai   45000
3    lama   33    Bali   11110

In [51]:
#conditional selection 
df[df["Age"]>30]

   Name  Age Country  salary
2  kunu   31   Dubai   45000
3  lama   33    Bali   11110

In [57]:
#conditional selection for two conditions
df[(df['Age']>30) & (df['Country'] == 'Bali')]

   Name  Age Country  salary
3  lama   33    Bali   11110