In [1]:
import numpy as np
import pandas as pd

In [54]:
df1 = pd.DataFrame({
    'Name':['A','B'],
    'Marks':[80,90]
})

df2 = pd.DataFrame({
    'Name':['C','D'],
    'Marks':[70,60]
})

In [55]:
df1

  Name  Marks
0    A     80
1    B     90

In [56]:
df2

  Name  Marks
0    C     70
1    D     60

In [57]:
pd.concat([df1,df2],axis=0)

  Name  Marks
0    A     80
1    B     90
0    C     70
1    D     60

In [58]:
pd.concat([df1,df2],axis=1)

  Name  Marks Name  Marks
0    A     80    C     70
1    B     90    D     60

In [10]:
students = pd.DataFrame({
    'id':[1,2,3],
    'Name':['Ram','Shyam','Mohan']
})

marks = pd.DataFrame({
    'id':[1,2,3],
    'Marks':[90,85,88]
})

In [11]:
students

   id   Name
0   1    Ram
1   2  Shyam
2   3  Mohan

In [12]:
marks

   id  Marks
0   1     90
1   2     85
2   3     88

In [13]:
pd.merge(students,marks,on='id')

   id   Name  Marks
0   1    Ram     90
1   2  Shyam     85
2   3  Mohan     88

In [14]:
employees = pd.DataFrame({
    'id':[1,2,3,4],
    'Name':['A','B','C','D']
})

salary = pd.DataFrame({
    'id':[1,2],
    'Salary':[50000,60000]
})

In [15]:
employees

   id Name
0   1    A
1   2    B
2   3    C
3   4    D

In [16]:
salary

   id  Salary
0   1   50000
1   2   60000

In [27]:
pd.merge(employees,salary,how='left')

   id Name   Salary
0   1    A  50000.0
1   2    B  60000.0
2   3    C      NaN
3   4    D      NaN

In [22]:
df = pd.DataFrame({
    'Department':['IT','HR','IT','HR','Sales'],
    'Salary':[50000,40000,60000,45000,55000]
})

In [23]:
df

  Department  Salary
0         IT   50000
1         HR   40000
2         IT   60000
3         HR   45000
4      Sales   55000

In [26]:
a = df.groupby(['Department'])
for i , v in a:
    print(i)
    print(v)

('HR',)
  Department  Salary
1         HR   40000
3         HR   45000
('IT',)
  Department  Salary
0         IT   50000
2         IT   60000
('Sales',)
  Department  Salary
4      Sales   55000

In [29]:
df.groupby('Department')['Salary'].agg(['mean','max','min'])

               mean    max    min
Department
HR          42500.0  45000  40000
IT          55000.0  60000  50000
Sales       55000.0  55000  55000

In [30]:
df = pd.DataFrame({
    'Department':['IT','HR','IT','HR','Sales','IT']
})

In [31]:
df

  Department
0         IT
1         HR
2         IT
3         HR
4      Sales
5         IT

In [59]:
df.groupby(['Department']).size()

Department
HR       2
IT       3
Sales    1
dtype: int64

In [33]:
df1 = pd.DataFrame({
    'A':[1,2]
})

df2 = pd.DataFrame({
    'B':[3,4]
})

In [35]:
df1

   A
0  1
1  2

In [36]:
df2

   B
0  3
1  4

In [39]:
pd.concat([df1,df2],axis=1)

   A  B
0  1  3
1  2  4

In [40]:
sales = pd.DataFrame({
    'Category':['Electronics','Clothes','Electronics','Clothes'],
    'Sales':[1000,500,1500,700]
})

In [41]:
sales

      Category  Sales
0  Electronics   1000
1      Clothes    500
2  Electronics   1500
3      Clothes    700

In [42]:
sales.groupby('Category')['Sales'].sum()

Category
Clothes        1200
Electronics    2500
Name: Sales, dtype: int64

In [43]:
sales.groupby('Category')['Sales'].mean()

Category
Clothes         600.0
Electronics    1250.0
Name: Sales, dtype: float64

In [44]:
df1 = pd.DataFrame({
    'Name':['A','B','C']
}, index=[1,2,3])

df2 = pd.DataFrame({
    'Marks':[80,90,70]
}, index=[1,2,3])

In [45]:
df1

  Name
1    A
2    B
3    C

In [46]:
df2

   Marks
1     80
2     90
3     70

In [47]:
df1.join(df2)

  Name  Marks
1    A     80
2    B     90
3    C     70

In [48]:
orders = pd.DataFrame({
    'customer_id':[1,2,1,3,2],
    'Amount':[500,700,300,900,200]
})

In [49]:
orders

   customer_id  Amount
0            1     500
1            2     700
2            1     300
3            3     900
4            2     200

In [52]:
orders.groupby('customer_id')['Amount'].sum()

customer_id
1    800
2    900
3    900
Name: Amount, dtype: int64