In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.DataFrame({
    'Name':['A','B','C','D'],
    'Marks':[90,np.nan,85,np.nan]
})

df

  Name  Marks
0    A   90.0
1    B    NaN
2    C   85.0
3    D    NaN

In [4]:
df.isna()

    Name  Marks
0  False  False
1  False   True
2  False  False
3  False   True

In [5]:
df.fillna(0)

  Name  Marks
0    A   90.0
1    B    0.0
2    C   85.0
3    D    0.0

In [6]:
df = pd.DataFrame({
    'A':[1,2,np.nan,4],
    'B':[np.nan,5,6,7]
})
df

     A    B
0  1.0  NaN
1  2.0  5.0
2  NaN  6.0
3  4.0  7.0

In [7]:
df.isna().sum()

A    1
B    1
dtype: int64

In [8]:
df.dropna()

     A    B
1  2.0  5.0
3  4.0  7.0

In [9]:
df = pd.DataFrame({
    'Math':[90,np.nan,80],
    'Science':[70,60,np.nan]
})

In [14]:
df

   Math  Science
0  90.0     70.0
1   NaN     60.0
2  80.0      NaN

In [15]:
df.fillna({'Math':100,'Science':50})

    Math  Science
0   90.0     70.0
1  100.0     60.0
2   80.0     50.0

In [16]:
df = pd.DataFrame({
    'A':[1,np.nan,3],
    'B':[4,5,np.nan],
    'C':[7,8,9]
})

In [19]:
df.isnull().sum().sum()

np.int64(2)

In [29]:
df = pd.DataFrame({
    'Name':['Ram',np.nan,'Mohan'],
    'Age':[20,21,np.nan]
})

In [33]:
df['Age'].mean()

np.float64(20.5)

In [34]:
df.fillna({"Name":"unknown","Age":df['Age'].mean()})

      Name   Age
0      Ram  20.0
1  unknown  21.0
2    Mohan  20.5

In [36]:
df = pd.DataFrame({
    'A':[1,np.nan,np.nan],
    'B':[4,5,np.nan],
    'C':[7,8,9]
})

In [37]:
df

     A    B  C
0  1.0  4.0  7
1  NaN  5.0  8
2  NaN  NaN  9

In [38]:
df.dropna(how = 'all')

     A    B  C
0  1.0  4.0  7
1  NaN  5.0  8
2  NaN  NaN  9