In [1]:
import numpy as np
import pandas as pd

In [7]:
name = ["Rinku","Riya","Kunal"]
age = [20,21,22]

In [11]:
df = pd.DataFrame({
    "Name" : name,
    "Age" : age
})
print(data)

    Name  Age
0  Rinku   20
1   Riya   21
2  Kunal   22

In [12]:
df.shape

(3, 2)

In [13]:
df.columns

Index(['Name', 'Age'], dtype='object')

In [14]:
df.head()

    Name  Age
0  Rinku   20
1   Riya   21
2  Kunal   22

In [15]:
df[["Name"]]

    Name
0  Rinku
1   Riya
2  Kunal

In [16]:
df["Marks"] = [90,85,88]
df

    Name  Age  Marks
0  Rinku   20     90
1   Riya   21     85
2  Kunal   22     88

In [18]:
df[df["Age"]>20]

    Name  Age  Marks
1   Riya   21     85
2  Kunal   22     88

In [19]:
df[df["Marks"]>85]

    Name  Age  Marks
0  Rinku   20     90
2  Kunal   22     88

In [20]:
df.describe()

        Age      Marks
count   3.0   3.000000
mean   21.0  87.666667
std     1.0   2.516611
min    20.0  85.000000
25%    20.5  86.500000
50%    21.0  88.000000
75%    21.5  89.000000
max    22.0  90.000000

In [21]:
df

    Name  Age  Marks
0  Rinku   20     90
1   Riya   21     85
2  Kunal   22     88

In [24]:
df["Marks"].mean()

np.float64(87.66666666666667)

In [25]:
df.sort_values("Marks")

    Name  Age  Marks
1   Riya   21     85
2  Kunal   22     88
0  Rinku   20     90

In [27]:
data1 = pd.DataFrame({
    "Name" : ['A','B','C'],
    "Math" : [90,70,80],
    "Science" : [85,95,76]
})
data1

  Name  Math  Science
0    A    90       85
1    B    70       95
2    C    80       76

In [28]:
data1["Math"].mean()

np.float64(80.0)

In [29]:
data1["Math"].max()

np.int64(90)

In [30]:
data1[data1["Math"]>80]

  Name  Math  Science
0    A    90       85